# Generated by Django 2.0.3 on 2018-03-11 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.PositiveIntegerField(choices=[(0, 'Registration'), (1, 'Active'), (2, 'End')], default=0)),
                ('round', models.PositiveIntegerField(default=0)),
                ('wall', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('words_fld', models.TextField()),
                ('guess_mode', models.PositiveIntegerField(choices=[(0, 'First'), (1, 'Random'), (2, 'All')])),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ejudge_id', models.PositiveIntegerField()),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.Game')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='game.GameConfig'),
        ),
    ]
