# Generated by Django 2.0.3 on 2018-03-11 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20180311_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='title',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
