# Generated by Django 2.0.3 on 2018-03-12 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_game_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='id',
        ),
        migrations.AddField(
            model_name='game',
            name='prevent_guesses',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='ejudge_id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
