# Generated by Django 2.0.3 on 2018-03-12 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20180312_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='glob',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.Game'),
        ),
    ]
