# Generated by Django 2.0.3 on 2018-03-12 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20180312_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='teamleader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leaded_games', to='game.Player'),
        ),
    ]
