# Generated by Django 2.0.3 on 2018-03-14 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_game_teamleader'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameconfig',
            name='correct_shout_bonus',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='gameconfig',
            name='wrong_shout_bonus',
            field=models.IntegerField(default=5),
        ),
    ]
