# Generated by Django 2.0.3 on 2018-03-11 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('contest_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('wait_next_run', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.PositiveIntegerField()),
                ('create_time', models.DateTimeField()),
                ('user_id', models.PositiveIntegerField()),
                ('prob_id', models.PositiveIntegerField()),
                ('lang_id', models.PositiveIntegerField()),
                ('need_update', models.BooleanField()),
                ('status', models.IntegerField(choices=[(0, 'OK'), (1, 'Compilation Error'), (2, 'Run-Time Error'), (3, 'Time-Limit Exceeded'), (4, 'Presentation Error'), (5, 'Wrong Answer'), (6, 'Check Failed'), (7, 'Partial Solution'), (8, 'Accepted for Testing'), (9, 'Ignored'), (10, 'Disqualified'), (11, 'Pending'), (12, 'Memory Limit Exceeded'), (13, 'Security Violation'), (14, 'Style Violation'), (15, 'Wall Time Limit Exceeded'), (16, 'Pending Review'), (17, 'Rejected'), (18, 'Skipped'), (19, 'Synchronization Error'), (23, 'Summoned for Defence'), (95, 'Full Rejudge'), (96, 'Running'), (97, 'Compiled'), (98, 'Compiling'), (99, 'Rejudge'), (22, 'Empty Record'), (20, 'Virtual Start'), (21, 'VIrtual Stop')])),
                ('score', models.IntegerField()),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clerk.Contest')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together={('run_id', 'contest')},
        ),
    ]
