# Generated by Django 2.0.3 on 2018-03-11 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clerk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='wait_next_run',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
