# Generated by Django 2.0.3 on 2018-03-11 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest_id', models.PositiveIntegerField()),
                ('prob_id', models.PositiveIntegerField()),
                ('chars', models.CharField(max_length=32)),
            ],
        ),
    ]
