# Generated by Django 2.0.3 on 2018-03-13 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest_id', models.PositiveIntegerField()),
                ('prob_id', models.PositiveIntegerField()),
                ('ejudge_id', models.PositiveIntegerField()),
            ],
        ),
    ]
